
name: CI With Github Actions

on:
  push:
    tags: 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Create Release Draft
      uses: actions/create-release@latest
      id: create_release
      env: 
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ github.ref }}
       release_name: Release ${{ github.ref }}
       body: |+
            ## Bug fixes
            -
            ## Features
            -
            ## BREAKING CHANGES
            -
       draft: true
       prerelease: false
